public enum OpCode {
    CONSTANTE,
    SUMAR, RESTAR, MULTIPLICAR, DIVIDIR,
    NEGATIVO, NOT,
    IGUAL, MAYOR, MENOR,
    IMPRIMIR,
    SALTAR, SALTAR_SI_FALSO,
    LOOP,
    DEFINIR_GLOBAL, LEER_GLOBAL, ASIGNAR_GLOBAL,
    LEER_LOCAL, ASIGNAR_LOCAL,
    POP,
    RETORNAR
}